services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./static:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8087:80"
    depends_on:
      - php-fpm
      - deno-fallback
    restart: always

  php-fpm:
    image: php:fpm
    container_name: php-fpm
    volumes:
      - ./static:/var/www/html
    restart: always

  deno-fallback:
    image: denoland/deno
    container_name: deno-fallback
    volumes:
      - ./main.ts:/app/main.ts
      - ./ask.ts:/app/ask.ts
      - ./static:/app/static/
      - ./thoughts.txt:/app/thoughts.txt
    working_dir: /app
    command: ["run", "--allow-net", "--allow-write", "--allow-read", "main.ts"]
    ports:
      - "9090:8000"
    restart: always
