services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./static:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8087:80"
    depends_on:
      - php-fpm
      - deno-fallback
    restart: always

  php-fpm:
    image: php:fpm
    container_name: php-fpm
    volumes:
      - ./static:/var/www/html
    restart: always

  deno-fallback:
    image: denoland/deno
    container_name: deno-fallback
    volumes:
      - ./:/app/
    working_dir: /app
    command: ["run", "--allow-net", "--allow-write", "--allow-read", "main.ts"]
    ports:
      - "9090:9090"
    restart: always

  qdrant:
    image: qdrant/qdrant:v1.0.0
    container_name: qdrant
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    environment:
      # Optional: You can configure log levels, etc. here
      QDRANT__LOG_LEVEL: "INFO"

volumes:
  qdrant_data:
    driver: local
